apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {}
  name: instana-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {}
  name: instana-agent-role
rules:
- nonResourceURLs:
  - /version
  - /healthz
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  - replicasets
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - events
  - services
  - endpoints
  - nodes
  - pods
  - replicationcontrollers
  - componentstatuses
  - resourcequotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: instana-agent-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: instana-agent-role
subjects:
- kind: ServiceAccount
  name: instana-agent
  namespace: default
---
apiVersion: v1
data:
  configuration.yaml: |
    # Manual a-priori configuration. Configuration will be only used when the sensor
    # is actually installed by the agent.
    # The commented out example values represent example configuration and are not
    # necessarily defaults. Defaults are usually 'absent' or mentioned separately.
    # Changes are hot reloaded unless otherwise mentioned.

    # It is possible to create files called 'configuration-abc.yaml' which are
    # merged with this file in file system order. So 'configuration-cde.yaml' comes
    # after 'configuration-abc.yaml'. Only nested structures are merged, values are
    # overwritten by subsequent configurations.

    # Secrets
    # To filter sensitive data from collection by the agent, all sensors respect
    # the following secrets configuration. If a key collected by a sensor matches
    # an entry from the list, the value is redacted.
    #com.instana.secrets:
    #  matcher: 'contains-ignore-case' # 'contains-ignore-case', 'contains', 'regex'
    #  list:
    #    - 'key'
    #    - 'password'
    #    - 'secret'

    # Host
    #com.instana.plugin.host:
    #  tags:
    #    - 'dev'
    #    - 'app1'

    # Hardware & Zone
    #com.instana.plugin.generic.hardware:
    #  enabled: true # disabled by default
    #  availability-zone: 'zone'
kind: ConfigMap
metadata:
  name: instana-configuration
---
apiVersion: v1
data:
  key: S0VZLUhFUkU=
kind: Secret
metadata:
  name: instana-agent-secret
type: Opaque
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    chart: instana-agent-1.0.3
  name: instana-agent
spec:
  template:
    metadata:
      labels:
        app: instana-agent
    spec:
      containers:
      - env:
        - name: INSTANA_AGENT_LEADER_ELECTOR_PORT
          value: "42655"
        - name: INSTANA_ZONE
          value: k8s-cluster-name
        - name: INSTANA_AGENT_ENDPOINT
          value: saas-us-west-2.instana.io
        - name: INSTANA_AGENT_ENDPOINT_PORT
          value: "443"
        - name: INSTANA_AGENT_KEY
          valueFrom:
            secretKeyRef:
              key: key
              name: instana-agent-secret
        - name: JAVA_OPTS
          value: -Xmx170M -XX:+ExitOnOutOfMemoryError
        - name: INSTANA_AGENT_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: instana/agent:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /status
            port: 42699
          initialDelaySeconds: 75
          periodSeconds: 5
        name: instana-agent
        resources:
          limits:
            cpu: 1.5
            memory: 512Mi
          requests:
            cpu: 0.5
            memory: 512Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev
          name: dev
        - mountPath: /var/run/docker.sock
          name: run
        - mountPath: /sys
          name: sys
        - mountPath: /var/log
          name: log
        - mountPath: /etc/machine-id
          name: machine-id
        - mountPath: /root/configuration.yaml
          name: configuration
          subPath: configuration.yaml
      - args:
        - --election=instana
        - --http=0.0.0.0:42655
        - --id=$(INSTANA_AGENT_POD_NAME)
        env:
        - name: INSTANA_AGENT_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: gcr.io/google-containers/leader-elector:0.5
        livenessProbe:
          httpGet:
            path: /status
            port: 42699
          initialDelaySeconds: 75
          periodSeconds: 5
        name: instana-agent-leader-elector
        resources:
          requests:
            cpu: 0.1
            memory: 64Mi
      hostIPC: true
      hostNetwork: true
      hostPID: true
      serviceAccount: instana-agent
      volumes:
      - hostPath:
          path: /dev
        name: dev
      - hostPath:
          path: /var/run/docker.sock
        name: run
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /var/log
        name: log
      - hostPath:
          path: /etc/machine-id
        name: machine-id
      - configMap:
          name: instana-configuration
        name: configuration
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-example
spec:
  rules:
  - host: example.leaf.io
    http:
      paths:
      - backend:
          serviceName: example-svc
          servicePort: 80
